[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "OctoPrint-The-Helm"
version = "2.0.1"
description = "The Helm recovers failed prints that are still attached or must be re-seated on the bed."
authors = [
    {name = "Kenneth B Smith", email = "failed.print.resume.wizard@proton.me"}
]
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.7, <4"
dependencies = [
    "requests",
]

[tool.setuptools.packages.find]
include = [
    "octoprint_lazarus",
    "octoprint_lazarus.*",
]

[tool.setuptools.package-data]
octoprint_lazarus = [
    "templates/*.jinja2",
    "static/**/*",
]

[project.entry-points."octoprint.plugin"]
lazarus = "octoprint_lazarus"

[project.urls]
Homepage = "https://wizard.lazarus3dprint.com"
Source = "https://github.com/ksmith1489/lazarus-plugin"
Documentation = "https://wizard.lazarus3dprint.com/activate"
